[General]
# 此文件为 Apple Intelligence 调用 ChatGpt 专用分流配置文件（片段），不能单独使用，需要包含在主分流文件中，配置方法，选择主配置文件，i ▶ 通用 ▶ 包含配置，选择本配置文件

# Shadowrocket: 2026-05-12 11:13:51

# 小火箭 DNS 覆写一栏，需要加上#proxy，
# Cloudflare DoH 加密 DNS 地址 1：https://cloudflare-dns.com/dns-query#proxy
# Cloudflare DoH 加密 DNS 地址 2：https://security.cloudflare-dns.com/dns-query#proxy
# 这是 DNS 解析放到境外服务器，而不是网站访问走代理，所有 DNS 都走代理，本地运营商几乎看不到 DNS，泄露概率最低，但代价：国内网站可能变慢，CDN 可能错位，Apple/国内 App 可能异常。两者不冲突。不存在国内网站上不去的问题。不是国内网站走代理。
dns-server = https://cloudflare-dns.com/dns-query#proxy,https://security.cloudflare-dns.com/dns-query#proxy,https://dns.google/dns-query#proxy,https://8.8.8.8/dns-query#proxy,https://1.1.1.1/dns-query#proxy
# 劫持 DNS：8.8.8.8:53，正常情况下部分应用可能不会遵循系统设置，而用自行指定的 DNS 服务器，偷偷通过传统的 53 端口发，此设置小火箭会拦截这类传统的请求，并统—接管处理，这样可以有效减少 DNS 泄露的风险
hijack-dns = 8.8.8.8:53

update-url = https://raw.githubusercontent.com/XGithub0/Shadowrocket/refs/heads/main/Apple%20Intelligence.conf


[Rule]
# Update 20251121
DOMAIN-SUFFIX, gateway.icloud.com,Proxy
DOMAIN-SUFFIX, apple-relay.apple.com,Proxy
DOMAIN-SUFFIX, apple-relay.fastly-edge.com,Proxy
DOMAIN-SUFFIX, apple-relay.cloudflare.com,Proxy
DOMAIN-SUFFIX, guzzoni.apple.com,Proxy
DOMAIN-SUFFIX, cp4.cloudflare.com,Proxy
DOMAIN-SUFFIX, gspe1-ssl.ls.apple.com,Proxy
DOMAIN-SUFFIX, smoot.apple.com,Proxy
DOMAIN-SUFFIX, apple-relay.akamaized.net,Proxy
DOMAIN-SUFFIX, apple-relay.mask.apple-dns.net,Proxy
