# 此文件为 Apple Intelligence 分流专用配置文件，不能单独使用，需要包含在主分流文件中，使用方法，选择主配置文件，i ▶ 通用 ▶ 包含配置，选择本配置文件。
# Update 20251112
# 写在规则外的内容，导入Shadowrocket 后不显示，故在 General 中再添加说明

[General]
# 此文件为 Apple Intelligence 分流专用配置文件，不能单独使用，需要包含在主分流文件中，使用方法，选择主配置文件，i ▶ 通用 ▶ 包含配置，选择本配置文件。
# Update 20251112

[Rule]
DOMAIN-SUFFIX, gateway.icloud.com,Proxy
DOMAIN-SUFFIX, apple-relay.apple.com,Proxy
DOMAIN-SUFFIX, apple-relay.fastly-edge.com,Proxy
DOMAIN-SUFFIX, apple-relay.cloudflare.com,Proxy
DOMAIN-SUFFIX, guzzoni.apple.com,Proxy
DOMAIN-SUFFIX, cp4.cloudflare.com,Proxy
DOMAIN-SUFFIX, gspe1-ssl.ls.apple.com,Proxy
